# Generated by Django 6.0 on 2025-12-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='description',
        ),
        migrations.AddField(
            model_name='scheme',
            name='benefit_amount',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='caste',
            field=models.CharField(default='Any', max_length=20),
        ),
        migrations.AddField(
            model_name='scheme',
            name='gender',
            field=models.CharField(default='Any', max_length=10),
        ),
        migrations.AddField(
            model_name='scheme',
            name='priority_score',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='scheme_type',
            field=models.CharField(choices=[('Central', 'Central'), ('State', 'State')], default='Central', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheme',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Health', 'Health'), ('Women', 'Women'), ('Employment', 'Employment'), ('Agriculture', 'Agriculture'), ('Housing', 'Housing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
